### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by rabble** [staltz/amicispace#1]
I tried to clone, build, and run amicispace. I got NPM to install correctly and build but when i tried to run it i got this error. 

`┬─[rabble@r-mbp:~/c/s/amicispace]─[13:01:14]─[G:master=]
╰─>$ node index.js
/Users/rabble/code/ssb/amicispace/graph.js:113
async function* buildGraphNodes(sbot) {
              ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rabble/code/ssb/amicispace/index.js:14:55)
┬─[rabble@r-mbp:~/c/s/amicispace]─[13:02:29]─[G:master=]
╰─>$ node --version
v8.16.0
┬─[rabble@r-mbp:~/c/s/amicispace]─[13:03:51]─[G:master=]
╰─>$ npm --version
6.4.1`

**Comment by staltz** [comment]
Gotta use a higher version of node.js that supports async-await. I think version 10
